version: "3.1"

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./coolsite:/app
    working_dir: /app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: test_db_an
      DB_USER: andrii
      DB_PASSWORD: 5048
    depends_on:
      - postgres

  postgres:
    image: postgres:latest

    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: test_db_an
      POSTGRES_USER: andrii
      POSTGRES_PASSWORD: 5048
      POSTGRES_INITDB_ARGS: "-A md5"
