# Generated by Django 4.0.6 on 2022-08-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apple',
            options={'ordering': ['id'], 'verbose_name': 'Продукція Apple', 'verbose_name_plural': 'Продукція Apple'},
        ),
    ]
