# Generated by Django 4.0.6 on 2022-07-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_category_apple_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apple',
            options={'ordering': ['cat_id', 'title'], 'verbose_name': 'Продукція Apple', 'verbose_name_plural': 'Продукція Apple'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'категорії', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterField(
            model_name='apple',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apple.category', verbose_name='Категорії'),
        ),
        migrations.AlterField(
            model_name='apple',
            name='content',
            field=models.TextField(verbose_name='Текст статті'),
        ),
        migrations.AlterField(
            model_name='apple',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публікація'),
        ),
        migrations.AlterField(
            model_name='apple',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='apple',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='apple',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Час зміни'),
        ),
        migrations.AlterField(
            model_name='apple',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категорія'),
        ),
    ]
